#publish your docker image to github container registry
name: publish
on: [push]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: bal-test-notation

jobs:
  publish-Ballerina-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: azure-resource-login
        uses: Azure/azure-resource-login-action@v1.0.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # - name: Setup Notation with azure-kv plugin
      #   uses: Duffney/setup-notation@v1.0.0
      #   with:
      #     version: 1.0.0-rc.7
      #     key_name: balkeyzure
      #     certificate_key_id: https://balkey.vault.azure.net/keys/CertBal/d1580c9890d34888b23dcc03ed6d0dc0
      #     plugin_name: notation-azure-kv
          # plugin_version:  0.5.0-rc.1
      - name: Setup Go environment
        uses: actions/setup-go@v4.0.1
          
      - name: Setup and Install Notation 
        run : |
          curl -LO https://github.com/notaryproject/notation/releases/download/v1.0.0-rc.7/notation_1.0.0-rc.7_linux_amd64.tar.gz
          tar -xvzf notation_1.0.0-rc.7_linux_amd64.tar.gz
          sudo mkdir notation-cli
          mv notation notation-cli
          echo "export PATH=/notation-cli:\$PATH" >> $HOME/.bashrc
          source $HOME/.bashrc

      - name: Verify Notation Installation
        run: |
          echo $PATH
          notation version

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Ballerina Docker image
        run: |

          docker build --no-cache=true . --tag ${{ env.REGISTRY }}/miranlfk/${{ env.IMAGE_NAME }}:v${{ github.run_number }}
          docker run ${{ env.REGISTRY }}/miranlfk/${{ env.IMAGE_NAME }}:v${{ github.run_number }}
          docker push ${{ env.REGISTRY }}/miranlfk/${{ env.IMAGE_NAME }}:v${{ github.run_number }}
        
      - name: Verify key generation
        run: notation key list 
     
      - name: Sign the published Docker image
        env: 
          password: ${{ secrets.GITHUB_TOKEN }}
        run: notation sign ${{ env.REGISTRY }}/miranlfk/${{ env.IMAGE_NAME }}:v${{ github.run_number }}
        