#publish your docker image to github container registry
name: publish
on: [push]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: bal-test-notation

jobs:
  publish-Ballerina-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: azure-resource-login
        uses: Azure/azure-resource-login-action@v1.0.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Setup Notation with azure-kv plugin
        uses: Duffney/setup-notation@v1.0.0
        with:
          version: 1.0.0-rc.7
          key_name: balkeyzure
          certificate_key_id: ${{ secrets.AZURE_KEY }}
          plugin_name: notation-azure-kv
          plugin_version:  0.5.0-rc.1
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Notation Login
      #   run: |
      #     notation login ghcr.io -u ${{ secrets.NOTATION_USERNAME }} -p ${{ secrets.NOTATION_PASSWORD }}

      - name: Build the Ballerina Docker image
        run: |

          docker build --no-cache=true . --tag ${{ env.REGISTRY }}/miranlfk/${{ env.IMAGE_NAME }}:v${{ github.run_number }}
          docker run ${{ env.REGISTRY }}/miranlfk/${{ env.IMAGE_NAME }}:v${{ github.run_number }}
          docker push ${{ env.REGISTRY }}/miranlfk/${{ env.IMAGE_NAME }}:v${{ github.run_number }}

      - name: Verify key generation
        run: notation key list 
     
      - name: Sign the published Docker image
        run: | 
          notation sign ${{ env.REGISTRY }}/miranlfk/${{ env.IMAGE_NAME }}:v${{ github.run_number }} -u ${{ secrets.NOTATION_USERNAME }} -p ${{ secrets.NOTATION_PASSWORD }}
        