#publish your docker image to github container registry
name: publish
on: [push]
jobs:
  publish-Ballerina-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Ballerina Docker image
        run: |
          docker build --no-cache=true . --tag ghcr.io/miranlfk/bal-test-notation:latest
          docker run ghcr.io/miranlfk/bal-test-notation:latest
          docker push ghcr.io/miranlfk/bal-test-notation:latest
          